version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: btc_forecast
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.0
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow

  # More services to be added...

volumes:
  postgres_data:

